name: Pin to Pinata

on:
  push:
    branches:
      - main

jobs:
  pin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '24'   # <- important!
      - run: npm install pinata-sdk
      - run: node pin.js
        env:
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
